# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ba8b127e3585cabb00947abb5f755ef6693cca2dcbdfafbcb36d84725f064a418422dc252660462f2a80fdbf8b349499eaf848a77d92abef4cdf94c214eb87c

test:
  secret_key_base: d6fbceddadf9702b8c2eafe8f4fdebb749b57e271d5161f62349fe27637738e8d01775f715f6df4acdcdcba45e68ee571662209db31b09158b750d39128b09b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
